name: Build Tauri Windows App

on:
  push:
    branches:
      - svelte-rewrite
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm install

      - name: Bump Tauri Version
        shell: bash
        run: |
          jq '.version = "0.0.5-dev.${{ github.run_number }}"' src-tauri/tauri.conf.json > tmp.json && mv tmp.json src-tauri/tauri.conf.json

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: dev-build
          releaseName: 'Latest Dev Build'
          releaseBody: 'Automatically built from the latest commit on the svelte-rewrite branch.'
          releaseDraft: false
          prerelease: true
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
